export const sampleEvents = [
  // TECH
  {
    id: "1",
    title: "Nairobi Startup Mixer",
    description: "Meet founders, investors, and builders in Nairobi’s startup scene.",
    category: "Tech",
    city: "Nairobi",
    venue: "Westlands Hub",
    startDate: "2026-03-14",
    time: "18:00",
    price: 1000,
    isFree: false,
    tags: ["networking", "startup", "tech"],
    image: "/images/events/startup.jpg",
  },
  {
    id: "2",
    title: "AI Builders Meetup",
    description: "Discuss AI tools, LLMs, and real-world applications.",
    category: "Tech",
    city: "Nairobi",
    venue: "iHub",
    startDate: "2026-03-20",
    time: "17:30",
    price: 0,
    isFree: true,
    tags: ["ai", "machine learning", "developers"],
    image: "/images/events/ai.jpg",
  },
  {
    id: "3",
    title: "Web3 & Blockchain Summit",
    description: "Explore crypto, DeFi, and blockchain innovation in Africa.",
    category: "Tech",
    city: "Nairobi",
    venue: "KICC",
    startDate: "2026-04-02",
    time: "09:00",
    price: 3000,
    isFree: false,
    tags: ["blockchain", "crypto", "web3"],
    image: "/images/events/blockchain.jpg",
  },

  // MUSIC
  {
    id: "4",
    title: "Afrobeats Night",
    description: "Dance to the hottest Afrobeats and Amapiano tracks.",
    category: "Music",
    city: "Nairobi",
    venue: "The Alchemist",
    startDate: "2026-03-15",
    time: "21:00",
    price: 1200,
    isFree: false,
    tags: ["music", "party", "afrobeats"],
    image: "/images/events/afrobeats.jpg",
  },
  {
    id: "5",
    title: "Live Jazz Evening",
    description: "Relax with smooth live jazz performances.",
    category: "Music",
    city: "Nairobi",
    venue: "Alliance Française",
    startDate: "2026-03-22",
    time: "19:00",
    price: 800,
    isFree: false,
    tags: ["jazz", "live music"],
    image: "/images/events/jazz.jpg",
  },
  {
    id: "6",
    title: "Gengetone Fest",
    description: "Top Kenyan artists performing live.",
    category: "Music",
    city: "Nairobi",
    venue: "Carnivore Grounds",
    startDate: "2026-04-05",
    time: "16:00",
    price: 1500,
    isFree: false,
    tags: ["gengetone", "concert", "party"],
    image: "/images/events/concert.jpg",
  },

  // BUSINESS
  {
    id: "7",
    title: "Entrepreneurship Masterclass",
    description: "Learn how to build and scale a startup.",
    category: "Business",
    city: "Nairobi",
    venue: "Nairobi Garage",
    startDate: "2026-03-25",
    time: "14:00",
    price: 2000,
    isFree: false,
    tags: ["business", "startup", "growth"],
    image: "/images/events/business.jpg",
  },
  {
    id: "8",
    title: "Investment & Wealth Forum",
    description: "Insights into investing, stocks, and wealth creation.",
    category: "Business",
    city: "Nairobi",
    venue: "Radisson Blu",
    startDate: "2026-04-10",
    time: "10:00",
    price: 2500,
    isFree: false,
    tags: ["investment", "finance", "wealth"],
    image: "/images/events/finance.jpg",
  },

  // FOOD & SOCIAL
  {
    id: "9",
    title: "Nairobi Food Festival",
    description: "Taste amazing dishes from top chefs and vendors.",
    category: "Food",
    city: "Nairobi",
    venue: "Carnivore Grounds",
    startDate: "2026-04-12",
    time: "12:00",
    price: 1200,
    isFree: false,
    tags: ["food", "festival", "social"],
    image: "/images/events/food.jpg",
  },
  {
    id: "10",
    title: "Wine & Cheese Night",
    description: "A classy evening of wine tasting and networking.",
    category: "Food",
    city: "Nairobi",
    venue: "Villa Rosa Kempinski",
    startDate: "2026-03-28",
    time: "19:30",
    price: 3500,
    isFree: false,
    tags: ["wine", "luxury", "social"],
    image: "/images/events/wine.jpg",
  },

  // ART & CULTURE
  {
    id: "11",
    title: "Art & Culture Exhibition",
    description: "Experience contemporary African art.",
    category: "Art",
    city: "Nairobi",
    venue: "Nairobi Gallery",
    startDate: "2026-03-30",
    time: "11:00",
    price: 500,
    isFree: false,
    tags: ["art", "gallery", "culture"],
    image: "/images/events/art.jpg",
  },

  // FITNESS & OUTDOORS
  {
    id: "12",
    title: "Karura Forest Run",
    description: "Join a fun community run in Karura Forest.",
    category: "Fitness",
    city: "Nairobi",
    venue: "Karura Forest",
    startDate: "2026-03-16",
    time: "07:00",
    price: 0,
    isFree: true,
    tags: ["fitness", "run", "outdoors"],
    image: "/images/events/run.jpg",
  },
  {
    id: "13",
    title: "Yoga & Wellness Retreat",
    description: "Relax and recharge with yoga and meditation.",
    category: "Fitness",
    city: "Nairobi",
    venue: "Ngong Hills",
    startDate: "2026-04-18",
    time: "08:00",
    price: 2000,
    isFree: false,
    tags: ["yoga", "wellness", "health"],
    image: "/images/events/yoga.jpg",
  },

  // EDUCATION
  {
    id: "14",
    title: "Data Science Bootcamp Intro",
    description: "Kickstart your journey into data science.",
    category: "Education",
    city: "Nairobi",
    venue: "Moringa School",
    startDate: "2026-04-01",
    time: "10:00",
    price: 0,
    isFree: true,
    tags: ["data", "python", "machine learning"],
    image: "/images/events/data.jpg",
  },
];