export const sampleEvents = [
  {
    id: "1",
    title: "Nairobi Startup Mixer",
    description: "A founder and builder networking evening for startups, freelancers, and investors.",
    category: "Networking",
    genre: "Business",
    city: "Nairobi",
    venue: "Westlands Hub",
    startDate: "2026-03-14",
    time: "18:00",
    price: 1000,
    isFree: false,
    tags: ["networking", "founders", "business", "startups"],
  },
  {
    id: "2",
    title: "Gospel Night Live",
    description: "A live gospel music worship experience with multiple local artists.",
    category: "Music",
    genre: "Gospel",
    city: "Nairobi",
    venue: "KICC",
    startDate: "2026-03-15",
    time: "19:00",
    price: 1500,
    isFree: false,
    tags: ["gospel", "music", "worship", "live performance"],
  },
  {
    id: "3",
    title: "Karura Family Picnic Day",
    description: "Outdoor family experience with games, food vendors, and live entertainment.",
    category: "Family",
    genre: "Outdoor",
    city: "Nairobi",
    venue: "Karura Forest",
    startDate: "2026-03-16",
    time: "11:00",
    price: 500,
    isFree: false,
    tags: ["family", "outdoor", "kids", "picnic"],
  },
  {
    id: "4",
    title: "Free Tech Community Meetup",
    description: "A developer meetup covering AI tools, frontend workflows, and product demos.",
    category: "Tech",
    genre: "Community",
    city: "Nairobi",
    venue: "iHub",
    startDate: "2026-03-13",
    time: "17:30",
    price: 0,
    isFree: true,
    tags: ["tech", "developers", "community", "ai"],
  },
  {
    id: "5",
    title: "Live Jazz Rooftop Session",
    description: "A chilled rooftop date-night experience with live jazz and dinner options.",
    category: "Music",
    genre: "Jazz",
    city: "Nairobi",
    venue: "Kilimani Rooftop",
    startDate: "2026-03-14",
    time: "20:00",
    price: 2500,
    isFree: false,
    tags: ["jazz", "date night", "live music", "chill"],
  },
];